# Development configuration
---
spring:
  profiles: dev

datasource:
  url: jdbc:postgresql://localhost:5432/template
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

jpa:
  default-schema: template
  ddl-auto: validate
  naming-strategy:
  dialect:

# Production configuration
---
spring:
  profiles: prod

datasource:
  url: jdbc:postgresql://localhost:5432/template
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

jpa:
  default-schema: template
  ddl-auto: validate
  naming-strategy:
  dialect:

